.\" Bash script for generating passwords.
.\" 2020 - 2025, Ivan Kmeťo
.\"
.\" CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
.\" https://creativecommons.org/publicdomain/zero/1.0/

.TH GENPWDSH "1" "2025-04-08" "Version 1.3.0" "User Commands"
.SH NAME
GenPwdSh \- Bash script for generating passwords.
.SH SYNOPSIS
.B genpwdsh
[\fI\,LENGTH\/\fR] [\fI\,METHOD\/\fR] [\fI\,INPUT\/\fR]
.SH DESCRIPTION
.TP
Generate Password (in) Shell: Bash script for generating passwords, released to the public domain.
.PP
.B "Use following options for more information:"
.TP
.B \-\-help
display help message and exit.
.TP
.B \-\-version
output version information and exit.
.SH LENGTH
.TP
Set character length of generated password as integer value greater than 0. Default length is \fB16\fP.
.SH METHOD
.TP
Set preferred method of generating password. Default method is \fB-openssl\fP.
.TP
.B \-b2 " "
generates password using OpenSSL digest function with BLAKE2s-256 message digest command.
.TP
.B \-b3 " "
generates password using BLAKE3 hash function of b3sum command line tool.
.TP
.B \-sha224 " "
generates password using OpenSSL digest function with SHA-3 224 message digest command.
.TP
.B \-sha256 " "
generates password using OpenSSL digest function with SHA-3 256 message digest command.
.TP
.B \-sha384 " "
generates password using OpenSSL digest function with SHA-3 384 message digest command.
.TP
.B \-sha512 " "
generates password using OpenSSL digest function with SHA-3 512 message digest command.
.TP
.B \-shake128 " "
generates password using OpenSSL digest function with SHA-3 SHAKE128 message digest command.
.TP
.B \-shake256 " "
generates password using OpenSSL digest function with SHA-3 SHAKE256 message digest command.
.TP
.B \-random " "
generates password using /dev/random.
.TP
.B \-urandom " "
generates password using /dev/urandom.
.TP
.B \-openssl " "
generates password using OpenSSL pseudo-random bytes generator.
.TP
.B \-gpg " "
generates password using GnuPG (option '--armor 2').
.SH INPUT
.TP
Set input value for generating password if available. By default, output of command \fBdate +%N%M%S\fP is used as input.
.SH AUTHOR
Written by Ivan Kmeťo.
