.\" Bash script for generating passwords.
.\" 2020 - 2021, Ivan Kmeťo
.\"
.\" CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
.\" https://creativecommons.org/publicdomain/zero/1.0/

.TH GENPWDSH "1" "September 2021" "Version 1.0.0" "User Commands"
.SH NAME
GenPwdSh \- Bash script for generating passwords.
.SH SYNOPSIS
.B genpwdsh
[\fI\,LENGTH\/\fR] [\fI\,METHOD\/\fR]
.SH DESCRIPTION
Generate Password (in) Shell: Bash script for generating passwords, released to the public domain.
.PP
.SS "Use following options for more information:"
.TP
\fB\-\-help\fR
display help message and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH METHOD
.PP
.BR \-sha224 " "
generates password using sha224sum.
.PP
.BR \-sha256 " "
generates password using sha256sum.
.PP
.BR \-sha384 " "
generates password using sha384sum.
.PP
.BR \-sha512 " "
generates password using sha512sum.
.PP
.BR \-b2 " "
generates password using b2sum.
.PP
.BR \-md5 " "
generates password using md5sum.
.PP
.BR \-random " "
generates password using /dev/random.
.PP
.BR \-urandom " "
generates password using /dev/urandom.
.PP
.BR \-openssl " "
generates password using OpenSSL.
.PP
.BR \-gpg " "
generates password using GnuPG (option '--armor 2').
.SH AUTHOR
Written by Ivan Kmeťo.
