.\" Bash script for generating passwords.
.\" 2020 - 2022, Ivan Kmeťo
.\"
.\" CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
.\" https://creativecommons.org/publicdomain/zero/1.0/

.TH GENPWDSH "1" "March 2022" "Version 1.2.0" "User Commands"
.SH NAME
GenPwdSh \- Bash script for generating passwords.
.SH SYNOPSIS
.B genpwdsh
[\fI\,LENGTH\/\fR] [\fI\,METHOD\/\fR] [\fI\,INPUT\/\fR]
.SH DESCRIPTION
.TP
Generate Password (in) Shell: Bash script for generating passwords, released to the public domain.
.PP
.B "Use following options for more information:"
.TP
\fB\-\-help\fR
display help message and exit
.TP
\fB\-\-version\fR
output version information and exit
.SH METHOD
.PP
.BR \-b2 " "
generates password using OpenSSL digest function with BLAKE2s-256 message digest command.
.PP
.BR \-sha224 " "
generates password using OpenSSL digest function with SHA-3 224 message digest command.
.PP
.BR \-sha256 " "
generates password using OpenSSL digest function with SHA-3 256 message digest command.
.PP
.BR \-sha384 " "
generates password using OpenSSL digest function with SHA-3 384 message digest command.
.PP
.BR \-sha512 " "
generates password using OpenSSL digest function with SHA-3 512 message digest command.
.PP
.BR \-shake128 " "
generates password using OpenSSL digest function with SHA-3 SHAKE128 message digest command.
.PP
.BR \-shake256 " "
generates password using OpenSSL digest function with SHA-3 SHAKE256 message digest command.
.PP
.BR \-random " "
generates password using /dev/random.
.PP
.BR \-urandom " "
generates password using /dev/urandom.
.PP
.BR \-openssl " "
generates password using OpenSSL pseudo-random bytes generator.
.PP
.BR \-gpg " "
generates password using GnuPG (option '--armor 2').
.SH AUTHOR
Written by Ivan Kmeťo.
