# Bash script for generating passwords.
# 2020, Ivan Kmeťo
#
# CC0 1.0 Universal (CC0 1.0) Public Domain Dedication
# https://creativecommons.org/publicdomain/zero/1.0/

install:
	cp genpwdsh.sh /usr/local/bin/genpwdsh
	chmod a+rx /usr/local/bin/genpwdsh

uninstall:
	rm /usr/local/bin/genpwdsh